### ISSUE TITLE
Redirect When No Resource 

### ISSUE THREAD

**Issue by rmaspero** [oivoodoo/devise_masquerade#100]
Hey,
Thanks for maintaining this gem! I've encountered a small bug in the controller line 25

```
      redirect_to(new_user_session_path) and return
```

Assumes the new_user_session_path exists but if using custom models e.g. an Admin logging in then this redirect breaks as the devise default route is in fact new_admin_session_path not new_user_session_path.

**Comment by oivoodoo** [comment]
Hi @rmaspero . Sorry for delay. I think I've just pushed the changes as 1.3.10 . hope it would work fine.
