### ISSUE TITLE
When expiration ends, it does not return to the original owner.

### ISSUE THREAD

**Issue by iprog21** [oivoodoo/devise_masquerade#102]
So when I masquerade one user. and it has time duration for being masquerade. when time duration ends, it didnt go back to the original owner like the behaviour of reverse masquerade when you click it manually. 

is auto reverse masquerade after time duration ends feature already included on the gem? or need to do some engineering to make that happen? 

thanks in advance. much appreciated if answer this quickly.

**Comment by oivoodoo** [comment]
Hi, @iprog21 Don't have in the gem auto go back to the owner. gem has only expiration on the token to do auth as a specific user. 

Probably it would require to do somehow the expirable sessions but I can't help with it. if you want to contribute, give it a try to add somehow the configurable option and patch the auth process for devise.

**Comment by iprog21** [comment]
hi @oivoodoo . thanks for your reply. actually ive already engineered it on the system that i'm working. 

what I did is. i've put a session variable with the current_user email on the `show` action. this snippet.

<img width="593" alt="Screen Shot 2022-03-14 at 11 48 07 PM" src="https://user-images.githubusercontent.com/12620242/158209412-7f185ba5-8930-48ba-8109-520b2f54e1a2.png">

this will trigger at the time that the owner will masquerade another user. 
then when time duration ends. when the user try to go somewhere on the page. the **before_action :redirect_expired_masquerade**  is waiting on **application_controller.rb**

<img width="754" alt="Screen Shot 2022-03-14 at 11 50 38 PM" src="https://user-images.githubusercontent.com/12620242/158210540-d02cd82f-73b4-40c4-9966-2cccaa3ba807.png">


then that how it works. sad to say but i don't how to contribute on the gem. and i have no knowledge yet on creating or contributing on any rub gems. but im I like to learn about that of development. if you have some good tutorials to learn. then I would be happy if you share it :) . thanks.
