### ISSUE TITLE
Upgrade Problems

### ISSUE THREAD

**Issue by Ancez** [oivoodoo/devise_masquerade#103]
Hi,

I've encountered several issues with the new updates done to this gem. Could someone explain to me how the new routes are generated? I.e. `masquerade_path` & the back route. Also, why are these routes now not showing within the `rails routes` command?

I'm working on an app which uses InertiaJs and now, I have to pass the masquerade_path via the serializer instead of relying on the Inertia `$routes.account_masquerade_path`.

```ruby
controllers/devise/masquerades_controller.rb:20
- redirect_to(new_user_session_path) and return
+ redirect_to(send("new_#{masqueraded_resource_name}_session_path")) and return
```

<img width="1085" alt="CleanShot 2022-03-31 at 11 22 53@2x" src="https://user-images.githubusercontent.com/32838548/161034280-bf21dc2a-eae7-443a-a1fa-fed3701859ff.png">

**Comment by oivoodoo** [comment]
@Ancez Hi.

Did you make the upgrade of the gem from what version? 

for my test app inside of the gem spec/dummy

rails routes | grep masquerade


           user_masquerade_index GET    /users/masquerade(.:format)            users/masquerades#show
      back_user_masquerade_index GET    /users/masquerade/back(.:format)       users/masquerades#back
     admin_user_masquerade_index GET    /admin_users/masquerade(.:format)      devise/masquerades#show
back_admin_user_masquerade_index GET    /admin_users/masquerade/back(.:format) devise/masquerades#back
        student_masquerade_index GET    /students/masquerade(.:format)         devise/masquerades#show
   back_student_masquerade_index GET    /students/masquerade/back(.:format)    devise/masquerades#back

**Comment by Ancez** [comment]
Hi @oivoodoo, thank you for your rapid response. I appreciate it

I'm upgrading from version 1.2.0 to 1.3.1. I've cloned the gem itself to play with the dummy. The dummy works as expected. But regardless of the dummy working; the `masquerade#show` route from `rails routes` is incorrect right? Surely it shouldn't be `_index`, and should include the masquerade `:id`. To me, it isn't following the Rails standard CRUD routes. 

This `user_masquerade_index_path` is wrong as it doesn't allow the user to be passed to it. Following from the dummy's example, using `masquerade_path(user)` works, but I don't understand where it's defined, how it's defined and why it is not showing in `rails routes` - should it be shown there?

Also, the code snipped provided in the Issue description, fixes the devise session so it would be good to get this sorted so this new version actually works for others. This is the main blocking issue preventing me from upgrading this gem.

**Comment by oivoodoo** [comment]
Hi @Ancez 

It's not exactly the show path in this case. URL generated has no id of the user. it's having the encoded value to be used for masquerade. 

```
/users/masquerade?masquerade=BAh7CEkiCGdpZAY6BkVUSSIlZ2lkOi8vZHVtbXkvVXNlci8yP2V4cGlyZXNfaW49NjAGOwBUSSIMcHVycG9zZQY7AFRJIg9tYXNxdWVyYWRlBjsAVEkiD2V4cGlyZXNfYXQGOwBUSSIdMjAyMi0wNC0wMVQwNzozODoxOC4zNTJaBjsAVA%3D%3D--6fd952c0e95b21813435edb2c0172eff750467bf&masqueraded_resource_class=User
``

it's the example of URL. I can rename show route to the other name. Also it is not the CRUD here. 

GET /masquerade + query params -> it's making the sign in. it is not the reading operation.

Also I don't understand the issue mentioned here:

```
controllers/devise/masquerades_controller.rb:20
- redirect_to(new_user_session_path) and return
+ redirect_to(send("new_#{masqueraded_resource_name}_session_path")) and return
```

Could you share more details about the problem? 

```
+ redirect_to(send("new_#{masqueraded_resource_name}_session_path")) and return
```

**Comment by itsNikolay** [comment]
@oivoodoo 
I got the same problem after gem upgrades:
- gem `rails` from 5.2.5 to 6.1.4.6 
- gem `device` from 4.6.2 to 4.8.1
- gem `devise_masqurade` from 0.6.5 to 1.3.9

before upgrade I had:
```ruby

                                            user_masquerade GET      /users/masquerade/:id(.:format)                                                                                 masquerades#show
                                 back_user_masquerade_index GET      /users/masquerade/back(.:format)                                                                                masquerades#back
```
after upgrade I have:
```ruby

                                      user_masquerade_index GET      /users/masquerade(.:format)                                                                                     devise/masquerades#show
                                 back_user_masquerade_index GET      /users/masquerade/back(.:format)                                                                                devise/masquerades#back
```
Is it possible to debug difference somehow ? Probably I could help with it?
