### ISSUE TITLE
Missing version tags

### ISSUE THREAD

**Issue by madleech** [oivoodoo/devise_masquerade#111]
Hi there, looks like tags for v1.3.10, 1.3.11 and 1.3.12 haven't been added? Also `version.rb` says `1.3.11` even though the latest version on rubygems is v1.3.12. Makes it a bit confusing trying to track down bugs in my code!!

Thanks.

**Comment by oivoodoo** [comment]
Hi @madleech is it ok to close this issue? I started to track the release versions by tags, github releases section and it's the same in rubygems.

Thank you!

**Comment by ioquatix** [comment]
Looks like the missing tags have been added so I would say good to close, thanks!

https://github.com/oivoodoo/devise_masquerade/releases/tag/v1.3.10
