### ISSUE TITLE
back_masquerade_path(current_user) broken in newer versions

### ISSUE THREAD

**Issue by jason-hobbs** [oivoodoo/devise_masquerade#117]
In versions < 2, this works perfectly:
back_masquerade_path(current_user)
In version 2 or greater, I get:
Couldn't find User with 'id'=admin-user
<img width="870" alt="Screenshot 2022-10-30 at 8 17 21 PM" src="https://user-images.githubusercontent.com/8509501/198912699-4e215aba-5840-4905-bbef-05759a180762.png">

**Comment by foundation-1** [comment]
+1

**Comment by oivoodoo** [comment]
@foundation-1 Hi everyone! Really sorry for having the issues. I will fix it during today/tomorrow. 

I added as session storage implementation like record.to_param. saving id of the record and then I do .find() probably you have something friendly id as part of your user models.

**Comment by jason-hobbs** [comment]
I am using friendly id.

**Comment by jason-hobbs** [comment]
I updated to 2.0.3 and am still having the issue whereas with < 1 it works fine.

**Comment by oivoodoo** [comment]
@frodsan the major release 2.x.x is using by default session based masquerading
