### ISSUE TITLE
RuntimeError: Could not find a valid mapping for nil

### ISSUE THREAD

**Issue by bbuchalter** [oivoodoo/devise_masquerade#13]
I've been seeing this pretty regularly, but can't figure out why. It seems the `owner_user` variable here is sometimes `nil`: https://github.com/oivoodoo/devise_masquerade/blob/master/app/controllers/devise/masquerades_controller.rb#L20

Perhaps the redirect was OK with occasional nils but `sign_in` is not. Should we add a conditional here?

Here's the backtrace:

```
[GEM_ROOT]/gems/devise-2.2.8/lib/devise/mapping.rb:42:in `find_scope!`
[GEM_ROOT]/gems/devise-2.2.8/lib/devise/controllers/helpers.rb:113:in `sign_in`
[GEM_ROOT]/bundler/gems/devise_masquerade-c65a2f5e0ad5/app/controllers/devise/masquerades_controller.rb:22:in `back`
```

**Comment by calebhaye** [comment]
+1

**Comment by calebhaye** [comment]
I didn't have much luck in figuring out why this was happening, but visiting /users/sign_out with logout via GET enabled seemed to resolve the matter. :-\ :-1:
