### ISSUE TITLE
View generators generates files with incorrect path

### ISSUE THREAD

**Issue by SijiaDavis** [oivoodoo/devise_masquerade#134]
## Describe the Bug

According to the [customize page view guide](https://administrate-demo.herokuapp.com/customizing_page_views), if we want to customize the template used for a page, we can provide our own as `/app/views/administrate/....html.erb`, and it will replace Administrate's own. I'd like to override `/app/views/administrate/application/show.html.erb`, so I used the generator command `rails generate administrate:views:show`, and it produced a file at the path `app/views/admin/application/show.html.erb` instead.

## Steps to Reproduce

* Run `rails generate administrate:views:show`.
* Notice that the file generated is in `/app/views/admin` instead of `/app/views/administrate`.

## Expected Behavior

Running the generators should result in files generated in the `/app/views/administrate` directory.

## Actual Behavior
Running the generators results in files generated in the `/app/views/admin` directory.

**Comment by SijiaDavis** [comment]
Wrong repo...Oops

**Comment by oivoodoo** [comment]
yeah :)
