### ISSUE TITLE
Masquerade not cleaning up session data

### ISSUE THREAD

**Issue by spencerldixon** [oivoodoo/devise_masquerade#135]
We ran into an interesting issue where our application would error out after 12 or so masquerade attempts. 

Looking at the session, it seems each masquerade would add a key value pair like the following...

`devise_masquerade_user_dcf2648d-188a-4e96-9822-47c2c6d4ab28_b438499f-05d4-42a8-bc40-e0e55cffbb48"=>"e923134a-263f-4f9f-9a22-a191b5e6d0e8`

...but then these don't get removed as you'd expect after heading back to the admin user. This would lead to our session becoming full quickly (especially since we're using UUIDs), and then throwing an error.

In the `cleanup_masquerade_owner_session` method here (https://github.com/oivoodoo/devise_masquerade/blob/ec616953226cbd426b7e0d9083ab36dcf89e363e/app/controllers/devise/masquerades_controller.rb#L169) we remove stuff from the session, but only remove the `skey` if we're using the cache as our storage method.

We overrode the `cleanup_masquerade_owner_session` method in our app and added a `session.delete(skey)` which solves the issue of these keys building up in the session when masquerading lots of users in a row, but wondered if this should not be the default in the gem? Let me know your thoughts!

**Comment by oivoodoo** [comment]
Hi @spencerldixon 

Do you mean to add this line like in PR https://github.com/oivoodoo/devise_masquerade/pull/136 ?

I don't see any breaking points now to add it. tests were passed for me. if it helps for you to skip the custom clear method, I will merge it and publish the new version.

Thank you!

**Comment by spencerldixon** [comment]
hey @oivoodoo ! I think that looks good to me and should help stop the overflow issue. Thank you so much for this and for the awesome gem!

**Comment by oivoodoo** [comment]
@spencerldixon I've just published `2.1.3` thank you for help!
