### ISSUE TITLE
Authorization (cancan) Order of Operations

### ISSUE THREAD

**Issue by baoist** [oivoodoo/devise_masquerade#19]
Per `README.md`:

> ## Custom controller for adding cancan for authorization
> 
> ```
> class Admin::MasqueradesController < Devise::MasqueradesController
>   def show
>     authorize!(:masquerade, User)
> 
>     super
>   end
> end
> ```

`save_masquerade_owner_session` is a `before_filter` on `Devise::MasqueradesController`.

This will cause the owner session to be set to the `current_user`. In my project this results in `user_masquerade?` to return true, and displaying a link to `back_masquerade_path(resource)` to be displayed; even though the masquerading failed.

**Comment by oivoodoo** [comment]
@baoist changed the process for authorization.

Now you should override masquerade_authorize! and masquerade_authorized?. Going to close the issue for now.
