### ISSUE TITLE
Original User Squashed on Multiple Requests to Devise::MasqueradesController#show

### ISSUE THREAD

**Issue by baoist** [oivoodoo/devise_masquerade#20]
If I start masquerading as a user and then visit the path to masquerade as a user (new or the same) the original user session is overwritten with the most recent masqueraded user.

e.g.
Start with user `A`.
`A` masquerades as user `B`.
`A` visits new masquerade path for user `C`.
Original user is set to `B` when it should be `A`.

This issue occurs around:

``` ruby
class Devise::MasqueradesController < DeviseController
  #[...]
  def save_masquerade_owner_session
    session[session_key] = send("current_#{resource_name}").id
  end
  #[...]
end
```

I resolved the issue locally by changing `save_masquerade_owner_session` to:

``` ruby
session[session_key] = send("current_#{resource_name}").id unless
  session[session_key]
```

**Comment by oivoodoo** [comment]
HI @baoist . it was fixed in #31 by @mcyoung . Thank you!
