### ISSUE TITLE
Authorize Resource

### ISSUE THREAD

**Issue by myebiz** [oivoodoo/devise_masquerade#21]
I am trying to override the masquerades controller to include "load_and_authorize_resource" but am not able to for some reason.

I've created /app/controllers/masquerades_controller.by with class MasqueradesController, but it doesn't get run. I tried class Admin::MasqueradesController as suggested in readme, but that doesn't get run (not sure what the Admin namespace refers to in this case either).

Any ideas on what I might be doing wrong?

**Comment by romeuhcf** [comment]
+1

**Comment by oivoodoo** [comment]
@myebiz @romeuhcf changed the process for authorization.

Now you should override `masquerade_authorize!` and `masquerade_authorized?`. Going to close the issue for now.
