### ISSUE TITLE
Using authorization with devise_masquerade

### ISSUE THREAD

**Issue by bastianwegge** [oivoodoo/devise_masquerade#33]
Hello everyone,

I'm using Pundit for authorization and I've noticed something strange. Please take a look at the following lines: https://github.com/oivoodoo/devise_masquerade/blob/master/app/controllers/devise/masquerades_controller.rb#L8-L12

I'm just wondering what this does. Since I'm experiencing weird behavior where a `User` that is not allowed to use `masquerade` is seeing the authorization error but can also see our masquerade partial. Are these lines necessary to be in a before_action? Cause they might break authorization flow.

**Comment by oivoodoo** [comment]
Hi @bastianwegge . To be honest I don't understand the issue with these lines. 

`save_masquerade_owner_session` should save original user id to session to make it possible to restore laster. If you don't want to render partial with masquerade button something like that you should wrap by your authorization function in your view to skip the rendering for partial.

something like that:

`<%= link_to("masquerade", ....) if user.can?(:masquerade) %>`

But you mean the different cases, could you share more details how to reproduce the issue and I can try to fix it?

Thank you!

**Comment by bastianwegge** [comment]
It's as simple as the basic integration of devise and masquerade. If the user is calling the masquerade route without being authorized, masquerade is returning true for the visual helper user_masquerade?. That is caused by the before_action saving the session.

**Comment by oivoodoo** [comment]
@bastianwegge lets close the issue in case if the new approach from `0.5.x` version is working for you. thank you!

**Comment by bastianwegge** [comment]
I will test it right away!

**Comment by bastianwegge** [comment]
works like a charm ! <3 Thank you very much!
