### ISSUE TITLE
Dummy app reports ActionNotFound

### ISSUE THREAD

**Issue by nitsujri** [oivoodoo/devise_masquerade#40]
Following the instructions and clicking `Login as` the reply is:

````
Started GET "/masquerades/1" for 127.0.0.1 at 2017-07-27 07:23:20 +0800
Processing by MasqueradesController#show as HTML
  Parameters: {"id"=>"1"}
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = 3 LIMIT 1
[Devise] Could not find devise mapping for path "/masquerades/1".
This may happen for two reasons:

1) You forgot to wrap your route inside the scope block. For example:

  devise_scope :user do
    get "/some/route" => "some_devise_controller"
  end

2) You are testing a Devise controller bypassing the router.
   If so, you can explicitly tell Devise which mapping to use:

   @request.env["devise.mapping"] = Devise.mappings[:user]
````

**Comment by oivoodoo** [comment]
Hi @nitsujri .

Could you share your routes.rb partially with devise settings there?

Thank you!

**Comment by nitsujri** [comment]
Hi @oivoodoo, thanks for responding so fast.

It's the dummy app inside of `spec/dummy`. So the routes file is here:

https://github.com/oivoodoo/devise_masquerade/blob/master/spec/dummy/config/routes.rb

My steps:

1. cloned the project
1. ran `bundle install`
1. ran `rake db:setup`
1. ran `bundle exec rails s`
1. visit `localhost:3000`
1. create an account
1. click `Login as`

And then I hit this error.

**Comment by oivoodoo** [comment]
@nitsujri can't reproduce the error. Sorry for so long reply, thank you anyway for reporting!
