### ISSUE TITLE
How to get the real user when using masquerade?

### ISSUE THREAD

**Issue by aristizabal95** [oivoodoo/devise_masquerade#43]
Hello, I installed this gem after realizing pretender would not work for me because it doesn't create or modifies the client cookies when logging as another user. 

I'm having some problems adapting my app to this change. I need to be able to get the real user instance to have some logic behind, like displaying the real user image or name. Pretender used two variables to allow this: current_user would get changed to the impersonalized user, while true_entity would hold the real user. 

Is there something like this in this gem? Is there a way to get the real user behind the masquerade?
I know there is functionality to get back to your real user within this gem, as described on the readme. But I can't find a way to store the real user as a variable to do some logic with it.

**Comment by oivoodoo** [comment]
Hi @aristizabal95 

I've just checked the codebase it looks like it would be possible to restore owner of masquerade action by using controller helper:

```
#{name}_masquerade_owner
```

where #{name} could be `user` or other devise model.

Could you verify it?
