### ISSUE TITLE
Version 0.6 pry?

### ISSUE THREAD

**Issue by chevinbrown** [oivoodoo/devise_masquerade#44]
This looks concerning to me: https://github.com/oivoodoo/devise_masquerade/commit/6b1460f36123e38d16391de6862e5ac7c32325f3#diff-3f96780b420f7f24f5d727515ecc71ffR38

![bitmoji](https://render.bitstrips.com/v2/cpanel/ec48e54c-1ede-452a-ba29-4d4f918ccf2a-bd2a7242-a669-4357-9204-8dfc136be16e-v1.png?transparent=1&palette=1&width=246)

**Comment by oivoodoo** [comment]
Heh. :) So tired sometimes. Thank you! Going to fix it in 3 hours.

**Comment by oivoodoo** [comment]
@chevinbrown could you use 0.6.1 instead? I don't see pry there

**Comment by chevinbrown** [comment]
We sure can! We got that PR bump by dependabot. We're still on 0.3x, but I'll manually update to 0.6.1.
