### ISSUE TITLE
Authorization failed when logged in as Admin and trying to impersonate User

### ISSUE THREAD

**Issue by artur79** [oivoodoo/devise_masquerade#49]
When I'm logged in as Admin and I'm trying to impersonate User I'm getting authorization error, looks like that action show in MasqueradesController is not even reached. Is is possible to use that gem having two models Admin (who impersonates) and Uses (who is impersonated one) ?

**Comment by oivoodoo** [comment]
Hi @artur79, don't think it would be possible to do it in this way. I will try to plan it as soon as I can to work on it or if you want to play a bit with code and have time, please go ahead I can help with review.

It sounds like reasonable feature to add. thank you!

**Comment by oivoodoo** [comment]
Hi @artur79 . Could you give a try to update the gem to the latest version 0.6.4? 

Probably it was the issue in masquerade controller and configuration. 

Thanks

**Comment by quentindemetz** [comment]
@artur79 How did you get this to work ?

**Comment by quentindemetz** [comment]
This doesn't work any more since release of 1.2.0

@oivoodoo any tips ?

**Comment by oivoodoo** [comment]
@quentindemetz it would require to have test case to reproduce your issue. Please ensure that you have cache enabled.

**Comment by quentindemetz** [comment]
It was the cache ! Thanks @oivoodoo
