### ISSUE TITLE
Problem with resource name

### ISSUE THREAD

**Issue by FrancescoMeneghini** [oivoodoo/devise_masquerade#50]
Hi, i've tried to use my resource name Instead of user, but it doesn't work if i don't configure the resource name with "config.masquerading_resource_name" on devise.rb (undocumented way).
This is my configuration:

Model:

```
class Organization < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :confirmable, :masqueradable
```
Controllers:

```
class ApplicationController < ActionController::Base
  before_action :masquerade_organization!
```

```
class MasqueradesController < Devise::MasqueradesController
  def show
    super
  end

  protected

  def masquerade_authorized?
    current_organization.superpower
  end
end
```
Routes:

```
Rails.application.routes.draw do
 devise_for :organizations, controllers: { masquerades: "masquerades" }
```
Devise.rb

```
config.masquerading_resource_name = 'organization'
  config.masqueraded_resource_name = 'organization'
```

**Comment by oivoodoo** [comment]
Hi @FrancescoMeneghini .

Could you please try to use

```
config.masquerading_resource_class=Organization
config.masqueraded_resource_class=Organization
```

**Comment by FrancescoMeneghini** [comment]
Your config is ok and also before was, but my problem is that i need to use multiple models
thanks :smile:

**Comment by oivoodoo** [comment]
Hi @FrancescoMeneghini .

Could you please try to use the latest version 0.6.4? Probably I understand your correctly and fixed it. 

Now it would be enough to specify:

```
config.masquerading_resource_class=User
config.masqueraded_resource_class=Organization
```

it would use `User.model_name.param_key` in case if you don't have `config.masquerading_resource_name` and `config.masqueraded_resource_name` specified.


Thanks for reporting it

**Comment by FrancescoMeneghini** [comment]
Is also possible to config not only **Organization** but also **Student** and other class in the same time?
For example i've got **Admin** that can log in as **Organization** or **Student** or **User**.
Like:
```
config.masquerading_resource_class=Admin
config.masqueraded_resource_class=[Organization, Student, User]
```
Thanks a lot

**Comment by oivoodoo** [comment]
@FrancescoMeneghini probably it would require to pass as part of masquerade request model name. Let me play with it on the weekend or tonight. Write you back.

**Comment by simonini** [comment]
Hi @oivoodoo, thanks for your fantastic gem, have you some news about this question? I'm also interested in this feature. Thanks again 😬

**Comment by oivoodoo** [comment]
@simonini Hey. Sorry, really busy these days. I will review it as soon as possible. Positive comments like a fuel for me :) thank you!

**Comment by oivoodoo-work** [comment]
@simonini the new version 1.1.0 would have automatically on `masquerade_path` support any kind of the model for `masqueraded_resource_class`. It would pass `masqueraded_resource_class` as query param.

**Comment by oivoodoo** [comment]
Going to close it for now. Hope it works as expected.
