### ISSUE TITLE
Rails 5.2 doesn't have Zeitwerk

### ISSUE THREAD

**Issue by svyatov** [oivoodoo/devise_masquerade#56]
Rails 5.2 doesn't have Zeitwerk but v1.0.0 of this gem brings this dependency, why?

I think it should be either optional based on Rails version or require Rails 6.

**Comment by oivoodoo** [comment]
Hi @svyatov . Please give a try the recent changes `1.1.0` . I've just merge #57

**Comment by oivoodoo** [comment]
@svyatov no more dep on Zeitwerk. Don't think it was required in `1.0.0`
