### ISSUE TITLE
Code duplication

### ISSUE THREAD

**Issue by n-rodriguez** [oivoodoo/devise_masquerade#60]
https://github.com/oivoodoo/devise_masquerade/blob/64acfa9d477ecb5cf66f762e3a0a81f11b6055a8/lib/devise_masquerade/models/masqueradable.rb#L27

**Comment by oivoodoo** [comment]
@n-rodriguez 😀 oh, thank you to find it.

**Comment by oivoodoo** [comment]
@n-rodriguez pushed the changes. thank you!
