### ISSUE TITLE
Expired token masquerades you as yourself

### ISSUE THREAD

**Issue by NDuggan** [oivoodoo/devise_masquerade#63]
The default value for `Devise.masquerade_expires_in` is 1 minute.

If you navigate to a page with a masquerade link:
```ruby
<%= link_to "Login As", masquerade_path(user) %>
```

Wait 1 minute (or whatever your timeout is set to) and then click the "Login As" link, masquerade is activated. but for your own account. For example:

```
session["warden.user.user.key"][0][0] == session["devise_masquerade_user"]
=> true
```

And you will also be able to see the "Reverse Masquerade" link.

**Comment by wheresrobert** [comment]
I think I understand what's happening.

If the token doesn't find a user, the redirect to the new session url is triggered. 

Since you are already logged in, Devise pushes you to whatever route you choose as the after sign in route and in the process eats the flash message that would otherwise tell you that the user couldn't be found.

One of the first things that Devise Masquerade does is save the current user in a session key which is why it looks and functions like you're masqueraded but you're not.

**Comment by NDuggan** [comment]
@wheresrobert I believe you're right, as those are the paths I could see in the logs.

Is this considered a bug that will be fixed?

---

Also slightly off-topic, but the section of the README to include the before action confused me a little; I only plan on using the `masquerade_path` within a link, which I believe means I do not require the `before_action` - can you confirm?

```ruby
before_action :masquerade_user!
```

**Comment by wheresrobert** [comment]
> @wheresrobert I believe you're right, as those are the paths I could see in the logs.
> 
> Is this considered a bug that will be fixed?
> 
> Also slightly off-topic, but the section of the README to include the before action confused me a little; I only plan on using the `masquerade_path` within a link, which I believe means I do not require the `before_action` - can you confirm?
> 
> ```ruby
> before_action :masquerade_user!
> ```

I would consider it a bug personally, but I don't have the extra time right now to make a pull request. Maybe you can take a stab at it if you have the time. I'm sure @oivoodoo would appreciate it :)

As for your question, that method checks the params for the `masquerade` (by default) param and acts on it. You aren't required to use it if you are just using `masquerade_path`.

**Comment by oivoodoo** [comment]
@wheresrobert @wheresrobert you are right, it would be great to have the pull request 🙂 I can take a look anyway during the next few days. but it’s better to have help to be honest.

**Comment by wheresrobert** [comment]
I should also point out that I believe this same code causes the "You are already signed in" issue in development mode.

Because there is no cache store, the masquerade key can't be found when looking up the user so the whole process described above happens in that scenario as well.

**Comment by NDuggan** [comment]
@oivoodoo OK, I'll see what I can do.

@wheresrobert with regards to the development gotcha (having to enable `rails dev:cache`), is there a way to just disable one-time keys without overriding `find_by_masquerade_key`.

I would prefer to not use the expiring keys at all, as I'm using Pundit to manage authorisation, which will ensure you're logged in and have the correct permissions - so I feel the expiring key is overkill (in my use case).

**Comment by oivoodoo** [comment]
@NDuggan @wheresrobert on the weekend I can help with changes for gem if no one started to work on it. Thank you!

**Comment by NDuggan** [comment]
@oivoodoo I haven't started anything as I didn't get an answer regarding allowing the expiring keys to be optional.

I've personally just overwritten your method to suit my use case:
```ruby
def self.find_by_masquerade_key(_key)
  all
end
```

This solves the need to have caching turned on in development and stops the whole masquerading as yourself bug - which is exactly what I needed. I'm not bothered about expiring keys because I'm using Pundit policies to ensure the routes and buttons are protected.

**Comment by wheresrobert** [comment]
That monkey patch effectively reverts the changes made in the most recent release version, btw.

**Comment by mvz** [comment]
AIUI, the token is to prevent CSRF attacks: #45.

So reverting it may not be a good idea.

**Comment by NDuggan** [comment]
@mvz I understand it was to prevent CSRF, but as I'm using Devise for authentication and Pundit for authorisation, does the CSRF threat still apply to me? I've tried using a masquerade link from a "normal user" (who doesn't have access to masquerade based on my Pundit policy) and it doesn't let them masquerade as I get the expected 403 HTTP status.

I can add it back in (to my personal project) if necessary, as I'd rather be safer.

**Comment by mvz** [comment]
> does the CSRF threat still apply to me?

I don't know enough to answer that. Maybe @oivoodoo can explain?
