### ISSUE TITLE
Signed Global ID instead of Rails cache?

### ISSUE THREAD

**Issue by excid3** [oivoodoo/devise_masquerade#64]
I've run into the bug of not having the Rails cache enabled which means the masquerade token isn't retrievable and masquerading fails. I know this got added to the readme recently in the Troubleshooting section.

Is there any reason this couldn't use a Signed Global ID instead? They have expirations are are signed by the server. This would let you lookup tokens the same, but without having to rely on caching being enabled.

If there's interest, I'd be happy to make a PR for it. 👍

**Comment by oivoodoo** [comment]
Hi @excid3 .

it would be great to have it as optionable solution and specs as well to cover the new solution. I can help you with the review definitely. 

Thank you!

**Comment by oivoodoo** [comment]
Hi @excid3 .

it would be great to have it as optionable solution and specs as well to cover the new solution. I can help you with the review definitely. 

Thank you!

**Comment by excid3** [comment]
Took a stab at it last night. Was actually able to remove a lot of code using signed GlobalIDs. https://github.com/oivoodoo/devise_masquerade/compare/master...excid3:master

Was able to remove about 69 lines of code switching to GlobalID which I think is pretty slick. 🤘

The only functionality change is that the signed global IDs cannot be expired upon use like the Rails cache can. Since the tokens expire in 1 minute, that doesn't seem like too big of a deal to me, but it is a slight change in functionality so I wanted to note that.

Rails 4.2 and higher come with ActiveJob + GlobalID by default, so this shouldn't add any new dependencies unless someone removed ActiveJob from their app.

I think making this optional would just add complexity to the code base, and I don't know if it's worth it to support both mechanisms.

**Comment by oivoodoo** [comment]
@excid3 needs to take a closer the next few days. I got cold :) it's a bit scary changes for now anyway. Let me think about the possible merge of your idea with GlobalID. some guys are requesting me to have the option to skip expiration at all because of using `pundit` .

Thank you!

**Comment by excid3** [comment]
Interesting. What about Pundit causes problems with expirations?

**Comment by oivoodoo** [comment]
@excid3 it looks like, the dev want to have the option to remove expiration at all.  they don’t care about the expiration at all.

**Comment by excid3** [comment]
I wonder if setting `nil` in the masquerade settings would be good enough? I haven't tested to see what globalID does if you pass nil in for the expiration, but I think Rails cache handles a nil expiration correctly.

Could be good to add a couple tests for that.
