### ISSUE TITLE
Masquerade requires login prior

### ISSUE THREAD

**Issue by MatthewRuddy** [oivoodoo/devise_masquerade#71]
Hello 😄 Having an odd experience here - I've created a link to login as another user from ActiveAdmin, and it works, but only if someone has logged in as a `User` prior.

I've set the following config in `config/initializers/devise.rb`:

```
  config.masquerade_bypass_warden_callback = true
  config.masquerading_resource_class = User
  config.masquerading_resource_name = :user
  config.masqueraded_resource_class = AdminUser
  config.masqueraded_resource_name = :admin_user
```

If I log into the admin (`AdminUser` model), but don't log into a user account (`User` model), I'm required to log as a user before I can masquerade. Otherwise I'm prompted with devise's `User` login form.

In a situation where a support person is using the admin (`AdminUser`), but may not have an account as a `User` (signup is behind a paywall, in our case) this impedes us.

Am I missing something in the configuration, or is this intended behaviour? Thank you in advance 😄 😄

**Comment by MatthewRuddy** [comment]
Ok, managed to fix this. I had copied the config directly from the `README.md`, which I think may be wrong. I changed it to:

```
  config.masquerading_resource_class = AdminUser
  config.masquerading_resource_name = :admin_user
  config.masqueraded_resource_class = User
  config.masqueraded_resource_name = :user
```

That did the trick 👍

**Comment by oivoodoo** [comment]
@MatthewRuddy it looks like in the masquerade controller it requires to be signed in as masquerading_resource_class before_action: authenticate… . that’s why you saw the sign in form. you can always to have custom controller to skip this behaviour or manage authentication properly by custom code.

**Comment by MatthewRuddy** [comment]
@oivoodoo Thank you for you response 😄  I noticed this too, which lead me to believe my configuration was the wrong way around. It didn't make sense to require a user to already be signed in when masquerading as another user. The config too would suggest a `User` was masquerading as an `AdminUser` 😅 

I needed to trigger `authenticate_admin_user!` beforehand so swapping the config worked 👍 😄

**Comment by oivoodoo** [comment]
@MatthewRuddy it’s great that you solved it. and it’s great that it’s still useful 🙂 enjoy it.
