### ISSUE TITLE
Friendly ID

### ISSUE THREAD

**Issue by jason-hobbs** [oivoodoo/devise_masquerade#80]
In version 1.3.0 this works fine:
masqueraded_resource_class.friendly.find(params[:id])
Starting in 1.3.1 though, I get:
ActiveRecord::RecordNotFound - Couldn't find User without an ID:
  app/controllers/masquerades_controller.rb:6:in `find_resource'

**Comment by oivoodoo** [comment]
@jason-hobbs there is no id anymore in params. Now it was encoded by globalid.

**Comment by jason-hobbs** [comment]
Got it. Just took out the custom controller and it worked fine.  Thanks!
