### ISSUE TITLE
Custom url redirect not working.

### ISSUE THREAD

**Issue by remy727** [oivoodoo/devise_masquerade#91]
We have created `users/masquerades_controller.rb` file

```ruby
class Users::MasqueradesController < Devise::MasqueradesController
  protected

  def after_masquerade_path_for(resource)
    "/account"
  end

  def after_back_masquerade_path_for(resource)
    "/account"
  end
end
```

But it goes to `/` instead of `/account` page after masquerade.
Also same after finishing masquerade.

Both admin users and users are using the same table - `users`
Just checking if the user is admin by `user.is_admin = true`
Not sure this is related.

**Comment by oivoodoo** [comment]
Hi @remy727 come back from vacation in few days and take a look. Sorry for delay.

**Comment by remy727** [comment]
Thank you @oivoodoo 👍

**Comment by remy727** [comment]
Hi @jcquarto not sure what you mean.

**Comment by oivoodoo** [comment]
> @jcquarto, not sure what you mean.

Hi. have you tried to place in path functions pry to check if it was called?

Have you checked the debug logs after masquerade?

**Comment by oivoodoo** [comment]
I mean in 'after_masquerade_path_for' here
