### ISSUE TITLE
Missing tags for recent releases

### ISSUE THREAD

**Issue by adriancb** [oivoodoo/devise_masquerade#92]
👋 - first of all, thank you for dedicating your time to maintaining this library - it's appreciated!

We're upgrading from an older version of this library and realised that recent releases are missing corresponding tags? Would you mind explaining why that is?

https://rubygems.org/gems/devise_masquerade/versions has 1.3.4-1.3.8.
https://github.com/oivoodoo/devise_masquerade/releases only has < 1.3.4

It makes it difficult to track changes, either manually or via dependabot.

Thanks!

**Comment by oivoodoo** [comment]
Hi @adriancb 

to be honest I forgot to push tags because `rake release` creates tags automatically but I used to push without `--tags`.

**Comment by adriancb** [comment]
> Hi @adriancb
> 
> to be honest I forgot to push tags because `rake release` creates tags automatically but I used to push without `--tags`. I've just pushed the tags that I had it locally. Sorry for that.

No worries - thanks! It'll make it easier for the community to track changes and successfully call out issues or contribute.
